### ISSUE TITLE
Looks up invalid address: InternetAddress.lookup('example.com')

### ISSUE THREAD

**Issue by jorg1piano** [josehenriqueroveda/connection_verify#1]
Looks up invalid address: InternetAddress.lookup('example.com')

Does not work simply because of this...

Why not check google.com or facebook.com which both are pretty much guaranteed to be up.

**Comment by josehenriqueroveda** [comment]
Hello, thank you for feedback.
http://www.example.com is a valid address.
But I'll change it to google.com this week, as you suggested.

Have a nice weekend.

Em sex, 16 de out de 2020 11:43, jorg1piano <notifications@github.com>
escreveu:

**Comment by jorg1piano** [comment]
Awesome, ended up using another package, just thought you might wanted to know about the bug :)
